name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure build for amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86

      - name: Build solution
        run: call make.bat
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: none.exe

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: none.exe
          asset_name: none.exe
